### ISSUE TITLE
Req new usb wifi driver

### ISSUE THREAD

**Issue by Anemonastrum** [lynxnexy/immortalwrt#3]
Please add driver for rtl-8188eu

**Comment by lynxnexy** [comment]
Udah include coba di cek kembali
![Screenshot_2022-08-30-06-13-19-771_com termux](https://user-images.githubusercontent.com/81577496/187314654-e59979e2-0c23-4add-8329-60e9d4d38be5.jpg)

**Comment by lynxnexy** [comment]
silakan coba build.an terbaru gan, udah aq update driver nya..
