### ISSUE TITLE
Request adguardhome dan build untuk s905x3 (x96 max plus)

### ISSUE THREAD

**Issue by karnadii** [lynxnexy/immortalwrt#4]
Request adguardhome dan build untuk s905x3 (x96 max plus), terimakasih.

**Comment by lynxnexy** [comment]
tinggal sesuain dtb nya aja udah tersedia `meson-sm1-x96-max-plus.dtb` untuk `luci-app-adguardhome` menurut q kurang recommend, q ganti make `luci-app-adblock` yg lebih simpel dan powerfull tentunya..

klo emang lebih suka make `luci-app-adguardhome` bisa install secara manual bisa ikuti langkah ini:

```
opkg update
wget --no-check-certificate https://github.com/rufengsuixing/luci-app-adguardhome/releases/download/1.8-9/luci-app-adguardhome_1.8-9_all.ipk
opkg install luci-app-adguardhome_1.8-9_all.ipk
```

**Comment by karnadii** [comment]
Ok thanks. Nanti dicoba
